# prometheus.yml
global:
  scrape_interval: 5s  # How frequently to scrape targets

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']